name: Build and Release Flutter iOS

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allows manual triggering

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'
        channel: 'stable'
        
    - name: Get Flutter dependencies
      working-directory: ./app
      run: flutter pub get
      
    - name: Build iOS release
      working-directory: ./app
      run: flutter build ios --release --no-codesign
      
    - name: Create IPA
      working-directory: ./app/build/ios/iphoneos
      run: |
        mkdir -p Payload
        mv Runner.app Payload/
        zip -qq -r -9 lino.ipa Payload
        
    - name: Upload IPA as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: lino-ios-${{ github.run_number }}
        path: ./app/build/ios/iphoneos/lino.ipa
        retention-days: 30
